DEF = tiny
include $(CURDIR)/../include.mk

a-to-c-automatic-stepf-repl-script-spec.k.out: \
	KPROVE_OPTS += --spec-module A-TO-C-SPEC

a-to-c-automatic-repl-script-spec.k.out: \
	KPROVE_OPTS += --spec-module A-TO-C-SPEC

a-to-c-manual-repl-script-spec.k.out: \
	KPROVE_OPTS += --spec-module A-TO-C-SPEC
