# Specify additional command line arguments
- arguments: [-XTypeApplications]

# Control which extensions/flags/modules/functions can be used
- modules:
  - {name: [Data.Map], within: []}
  - {name: [System.FilePath.Posix], within: []}
  - name:
      - Prettyprinter
      - Prettyprinter.Render.Text
      - Prettyprinter.String
    within:
      - Pretty
      - Kore.JsonRpc.Types

# Ignore some builtin hints
# This warning should apply to Control.Exception.evaluate, but is mistakenly
# applied to Kore.Rewrite.SMT.Evaluator.evaluate.
- ignore: {name: "Redundant evaluate"}

# Corporate style
- ignore: {name: "Use tuple-section"}
- ignore: {name: "Use record patterns"}
- ignore: {name: "Use String"}
- ignore: {name: "Redundant id"}
- ignore: {name: "Use Just"}

# Ignore suggestions that may affect readability
- ignore: {name: "Eta reduce"}
- ignore: {name: "Avoid lambda using `infix`"}
- ignore: {name: "Use infix"}
- ignore: {name: "Use section"}
- ignore: {name: "Use <$>"}
- ignore: {name: "Use <&>"}
- ignore: {name: "Redundant flip"}
- ignore: {name: "Monad law, left identity"}
- ignore: {name: "Monoid law, left identity"}
- ignore: {name: "Replace case with maybe"}
- ignore: {name: "Hoist not"}
- ignore: {name: "Redundant bracket"}
- ignore: {name: "Fuse foldr/fmap"}

# Ignore suggestions to reduce duplication, because:
#  - High rate of false positives
#  - Suggestions are often not applicable
#  - Difficult to ignore suggestion locally
#  - Only detects exact duplication of text, not anything interesting
- ignore: {name: "Reduce duplication"}

# The placement of lambdas affects inlining.
- ignore: {name: Redundant lambda}

# Testing class laws
- ignore: {name: "Functor law", within: [Test.Data.Sup, Test.ListT]}
- ignore: {name: "Use /=", within: [Test.Data.Sup]}
- ignore: {name: "Alternative law, left identity", within: [Test.ListT]}
- ignore: {name: "Alternative law, right identity", within: [Test.ListT]}
- ignore: {name: "Monad law, right identity", within: [Test.ListT]}
- ignore: {name: "Use >=>", within: [Test.ListT]}
- ignore: {name: "Redundant id", within: [Test.ListT]}

# LANGUAGE Strict
- ignore: {name: "Redundant irrefutable pattern"}

- ignore:
    name: Use camelCase
    within:
      - Test.Terse
      - Test.Kore.Rewrite.Axiom.Evaluate
      - Test.Kore.Rewrite.Axiom.Matcher
      - Test.Kore.Simplify.Overloading


# Unsuitable suggestions
- ignore:
    name: "Reduce duplication"
    within:
      - Kore.Builtin.Builtin
      - Kore.Builtin.List
      - Kore.Builtin.Symbols
      - Kore.Domain.Builtin
      - Kore.Exec
      - Kore.Internal.Conditional
      - Kore.Rewrite.Axiom.Matcher
      - Kore.Simplify.AndTerms
      - Kore.Parser.Parser
      - Main
- ignore:
    name: "Use fmap"
    within:
      - Kore.Rewrite.Step
      - SQL.SOP
- ignore: {name: "Avoid lambda", within: [Kore.Rewrite.Function.Memo]}
- ignore:
    name: "Redundant bracket"
    within:
      - Kore.Internal.TermLike.TermLike


# Haskell names match K names
- ignore:
    name: "Use camelCase"
    within:
      - Kore.Builtin.Map.Map
      - Kore.Builtin.MapSymbols
      - Kore.Debug

- ignore:
    name: "Use newtype instead of data"
    within:
      - GlobalMain
      - Kore.JsonRpc.Types
      - Kore.Log.InfoExecDepth
      - Kore.Log.WarnUnexploredBranches

- ignore: {name: "Redundant compare", within: [Kore.Syntax.Id]}

- ignore:
    name: "Use void"
    within:
      - Test.Kore.Rewrite.Transition
