resolver: lts-22.23

nix:
  packages:
    - yq
    - z3
    - zlib

packages:
  - kore
  - kore-rpc-types
  - booster
  - dev-tools

# Dependency packages to be pulled from upstream that are not in the resolver
extra-deps:
  - tar-0.6.2.0
  - hashable-1.4.2.0
  - decision-diagrams-0.2.0.0
  - smtlib-backends-0.3
  - smtlib-backends-process-0.3
  - monad-validate-1.3.0.0
  - semialign-1.3

allow-newer: true

allow-newer-deps:
  - data-fix
  - text-short
  - these

ghc-options:
  "$everything": -haddock

local-bin-path: ./.build/kore/bin
