resolver: lts-22.23

nix:
  packages:
    - yq
    - z3
    - zlib

packages:
  - kore
  - kore-rpc-types
  - booster
  - dev-tools

# Dependency packages to be pulled from upstream that are not in the resolver
extra-deps:
  - hashable-1.4.2.0
  - decision-diagrams-0.2.0.0
  - smtlib-backends-0.3
  - smtlib-backends-process-0.3
  - typerep-map-0.6.0.0
  - monad-validate-1.3.0.0
  - github: goodlyrottenapple/tasty-test-reporter
    commit: b704130545aa3925a8487bd3e92f1dd5ce0512e2
  - github: goodlyrottenapple/profiteur
    commit: 7b30bbe6b2a6b72a5b4896f3a0eed5587a5bf465
  - ghc-prof-1.4.1.12@sha256:0146d3324470db81f6ed1d84b445f1d1aadaeb2e4e045876f5cd231a0946b713,2117
  
allow-newer: true

allow-newer-deps: 
  - data-fix
  - semialign
  - text-short
  - these
  - ghc-prof

ghc-options:
  "$everything": -haddock

local-bin-path: ./.build/kore/bin
