# coderabbit configuration, see https://coderabbit.ai/integrations/coderabbit-overrides.v2.json

language: en        # default
early_access: false # default
chat:
  auto_reply: false # default true

reviews:
  request_changes_workflow: false # default
  high_level_summary: true # default
  poem: false # default true
  review_status: false # default true
  collapse_walkthrough: false # default
  path_filters: [] # file patterns (glob patterns) to exclude in a review
  path_instructions: [] # adds some phrases (like "make sure to document things" for file patterns. ???
  auto_review: 
    enabled: true # default
    ignore_title_keywords: [] # ignore PRs that have any of those words in the title
    labels: ["rabbit-review"] # restrict automated reviews to PRs with one of these labels 
    drafts: false # default
    base_branches: [] # target branches (other than default) for which to review PRs
