# HLint configuration file
#
# see `hlint --default` for help
################################

- arguments: [ -XOverloadedRecordDot ]

- ignore: { name: "Use <$>", name: "Move brackets to avoid $" }
