name: hs-backend-booster
version: '0.0.0'
github: "runtimeverification/hs-backend-booster"
license: BSD3
author: "Runtime Verification Inc"
maintainer: "jost.berthold@runtimeverification.com"
synopsis: A simple rewrite engine to accelerate K Framework's Haskell backend
description: See [README](README.md)
category: Language

extra-source-files:
- LICENSE
- package.yaml
- README.md
- stack.yaml
- test/parser/*
- cbits/*

default-extensions:
  BangPatterns
  DataKinds
  DefaultSignatures
  DeriveAnyClass
  DeriveGeneric
  DerivingStrategies
  DerivingVia
  DuplicateRecordFields
  EmptyCase
  FlexibleInstances
  FunctionalDependencies
  GADTs
  GeneralizedNewtypeDeriving
  ImportQualifiedPost
  KindSignatures
  LambdaCase
  MultiParamTypeClasses
  NamedFieldPuns
  OverloadedRecordDot
  OverloadedStrings
  PolyKinds
  ScopedTypeVariables
  StandaloneDeriving
  TupleSections
  TypeApplications
  TypeFamilies
  ViewPatterns

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -j6
library:
  dependencies:
  - aeson
  - aeson-pretty
  - array
  - base
  - binary
  - bytestring
  - casing
  - conduit
  - conduit-extra
  - containers
  - deepseq
  - deriving-aeson
  - exceptions
  - extra
  - filepath
  - ghc-trace-events
  - gitrev
  - hashable
  - hpp
  - json-rpc
  - kore-rpc-types
  - language-c
  - monad-logger
  - optparse-applicative
  - prettyprinter
  - recursion-schemes >= 5.2.2.3
  - regex-base
  - regex-pcre-builtin
  - stm
  - stm-conduit
  - syb
  - template-haskell
  - text
  - transformers
  - unix
  - unliftio
  - unordered-containers
  source-dirs: library
  build-tools:
    - happy
    - alex

executables:
  booster-dev:
    source-dirs: tools/booster-dev
    main: Server.hs
    dependencies:
    - base
    - containers
    - deepseq
    - hs-backend-booster
    - optparse-applicative
    - text
    ghc-options:
    - -rtsopts
    - -eventlog
    # - -threaded
    # - -with-rtsopts=-N
  rpc-client:
    source-dirs: tools/rpc-client
    main: RpcClient
    dependencies:
      - aeson
      - aeson-pretty
      - base
      - bytestring
      - clock
      - directory
      - extra
      - hs-backend-booster
      - network
      - network-run
      - optparse-applicative
      - process
      - text
      - vector
    ghc-options:
      - -rtsopts
  parsetest:
    source-dirs: tools/parsetest
    main: Parsetest.hs
    dependencies:
      - base
      - containers
      - deepseq
      - directory
      - filepath
      - hs-backend-booster
      - prettyprinter
      - text
      - transformers
    ghc-options:
    - -rtsopts
  parsetest-binary:
    source-dirs: tools/parsetest-binary
    main: ParsetestBinary.hs
    dependencies:
      - base
      - binary
      - bytestring
      - containers
      - hs-backend-booster
      - text
    ghc-options:
    - -rtsopts
  dltest:
    source-dirs: tools/dltest
    main: Dltest.hs
    dependencies:
      - base
      - directory
      - hs-backend-booster
      - unix
    ghc-options:
    - -rtsopts
  eventlog-parser:
    source-dirs: tools/eventlog-parser
    main: EventlogParser.hs
    dependencies:
      - aeson
      - base
      - binary
      - bytestring
      - containers
      - directory
      - filepath
      - ghc-events
      - hashable
      - hs-backend-booster
      - optparse-applicative
      - text
      - transformers
      - unix
      - unordered-containers
    ghc-options:
    - -rtsopts

  kore-rpc-booster:
    source-dirs: tools/booster
    main: Server.hs
    dependencies:
      - aeson
      - base
      - casing
      - clock
      - conduit-extra
      - containers
      - deepseq
      - exceptions
      - extra
      - hs-backend-booster
      - json-rpc
      - kore
      - kore-rpc-types
      - monad-logger
      - optparse-applicative
      - prettyprinter
      - stm
      - text
      - transformers
    ghc-options:
    - -rtsopts

tests:
  unit-tests:
    source-dirs: unit-tests
    main: Driver.hs
    build-tools:
      - tasty-discover:tasty-discover
    dependencies:
    - base
    - binary
    - bytestring
    - containers
    - directory
    - filepath
    - hedgehog
    - hs-backend-booster
    - kore-rpc-types
    - monad-logger
    - process
    - tasty
    - tasty-golden
    - tasty-hedgehog
    - tasty-hunit
    - tasty-test-reporter
    - text
    - transformers
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

  llvm-integration:
    source-dirs: test/llvm-integration
    main: LLVM.hs
    dependencies:
      - base
      - bytestring
      - containers
      - filepath
      - hedgehog
      - hspec
      - hspec-hedgehog
      - hs-backend-booster
      - kore-rpc-types
      - process
      - text
      - transformers
