name: hs-backend-booster
version: '0.0.0'
github: "runtimeverification/hs-backend-booster"
license: BSD3
author: "Runtime Verification Inc"
maintainer: "jost.berthold@runtimeverification.com"
synopsis: A simple rewrite engine to accelerate K Framework's Haskell backend
description: See [README](README.md)
category: Language

extra-source-files:
- LICENSE
- package.yaml
- README.md
- stack.yaml

default-extensions:
  BangPatterns
  DefaultSignatures
  DeriveAnyClass
  DeriveGeneric
  DerivingStrategies
  DuplicateRecordFields
  FlexibleContexts
  GeneralizedNewtypeDeriving
  ImportQualifiedPost
  LambdaCase
  NamedFieldPuns
  ScopedTypeVariables
  TupleSections
  TypeApplications
  ViewPatterns

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -j6
library:
  dependencies:
  - aeson
  - aeson-pretty
  - base
  - bytestring
  - extra
  - text
  source-dirs: library

executables:
  hs-backend-booster:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - hs-backend-booster
    ghc-options:
    - -rtsopts
    # - -threaded
    # - -with-rtsopts=-N

tests:
  test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - bytestring
    - directory
    - filepath
    - hedgehog
    - hs-backend-booster
    - hspec
    - tasty
    - tasty-hspec
    - tasty-hedgehog
    - text
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
