name: hs-backend-booster
version: '0.0.0'
github: "runtimeverification/hs-backend-booster"
license: BSD3
author: "Runtime Verification Inc"
maintainer: "jost.berthold@runtimeverification.com"
synopsis: A simple rewrite engine to accelerate K Framework's Haskell backend
description: See [README](README.md)
category: Language

extra-source-files:
- LICENSE
- package.yaml
- README.md
- stack.yaml
- test/parser/*

default-extensions:
  BangPatterns
  DataKinds
  DefaultSignatures
  DeriveAnyClass
  DeriveGeneric
  DerivingStrategies
  DerivingVia
  DuplicateRecordFields
  FlexibleInstances
  FunctionalDependencies
  GADTs
  GeneralizedNewtypeDeriving
  ImportQualifiedPost
  KindSignatures
  LambdaCase
  MultiParamTypeClasses
  NamedFieldPuns
  OverloadedStrings
  ScopedTypeVariables
  StandaloneDeriving
  TupleSections
  TypeApplications
  TypeFamilies
  ViewPatterns

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -j6
library:
  dependencies:
  - aeson
  - aeson-pretty
  - array
  - base
  - bytestring
  - conduit
  - conduit-extra
  - containers
  - deriving-aeson
  - exceptions
  - extra
  - filepath
  - gitrev
  - json-rpc
  - monad-logger
  - mtl
  - optparse-applicative
  - prettyprinter
  - regex-base
  - regex-pcre-builtin
  - stm
  - stm-conduit
  - template-haskell
  - text
  - transformers
  - unliftio
  source-dirs: library

executables:
  hs-backend-booster:
    source-dirs: executable
    main: Main.hs
    build-tools:
      - happy
      - alex
    dependencies:
    - base
    - hs-backend-booster
    ghc-options:
    - -rtsopts
    # - -threaded
    # - -with-rtsopts=-N
  parsetest:
    source-dirs: tools/parsetest
    main: Parsetest.hs
    dependencies:
      - base
      - containers
      - deepseq
      - directory
      - filepath
      - hs-backend-booster
      - text
      - transformers
    ghc-options:
    - -rtsopts

tests:
  test-suite:
    source-dirs: test-suite
    main: Driver.hs
    build-tools:
      - tasty-discover:tasty-discover
      - happy
      - alex
    dependencies:
    - base
    - bytestring
    - directory
    - filepath
    - hedgehog
    - hs-backend-booster
    - tasty
    - tasty-golden
    - tasty-hedgehog
    - tasty-test-reporter
    - text
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
