resolver: lts-20.26

packages:
- .
- dev-tools

# Dependency packages to be pulled from upstream that are not in the resolver.
extra-deps:
  - chronos-1.1.5
  - co-log-0.5.0.0
  - decision-diagrams-0.2.0.0
  - smtlib-backends-0.3
  - smtlib-backends-process-0.3
  - typerep-map-0.5.0.0
  - monad-validate-1.2.0.1
  - git: https://github.com/runtimeverification/haskell-backend.git
    commit: e320d4b9dfe9fefa713311c99794ea5ba1950af1
    subdirs:
      - kore
      - kore-rpc-types

# Control whether we use the GHC we find on the path
# system-ghc: true

# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]

# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor

local-bin-path: ./.build/booster/bin

allow-newer: true
