DEF := bmc
include $(CURDIR)/../../../include.mk

pass-1-bmc-spec.k.out: KBMC_DEPTH = 20
pass-2-bmc-spec.k.out: KBMC_DEPTH = 10
pass-3-bmc-spec.k.out: KBMC_DEPTH = 20

fail-1-bmc-spec.k.out: KBMC_DEPTH = 20
fail-2-bmc-spec.k.out: KBMC_DEPTH = 20
fail-3-bmc-spec.k.out: KBMC_DEPTH = 20
fail-4-bmc-spec.k.out: KBMC_DEPTH = 20
