name: hs-backend-booster-dev-tools
version: '0.1.74'
github: "runtimeverification/hs-backend-booster"
license: BSD3
author: "Runtime Verification Inc"
maintainer: "jost.berthold@runtimeverification.com"
synopsis: Dev-tools for hs-backend-booster
category: Language

extra-source-files:
- LICENSE
- package.yaml

default-extensions:
  BangPatterns
  DataKinds
  DefaultSignatures
  DeriveAnyClass
  DeriveGeneric
  DerivingStrategies
  DerivingVia
  DuplicateRecordFields
  EmptyCase
  FlexibleInstances
  FunctionalDependencies
  GADTs
  GeneralizedNewtypeDeriving
  ImportQualifiedPost
  KindSignatures
  LambdaCase
  MultiParamTypeClasses
  NamedFieldPuns
  OverloadedRecordDot
  OverloadedStrings
  PolyKinds
  ScopedTypeVariables
  StandaloneDeriving
  TupleSections
  TypeApplications
  TypeFamilies
  ViewPatterns

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -j6

executables:
  booster-dev:
    source-dirs: booster-dev
    main: Server.hs
    dependencies:
    - base
    - containers
    - conduit-extra
    - deepseq
    - directory
    - fast-logger
    - hs-backend-booster
    - kore-rpc-types
    - monad-logger
    - optparse-applicative
    - text
    - transformers
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
  parsetest:
    source-dirs: parsetest
    main: Parsetest.hs
    dependencies:
      - base
      - containers
      - deepseq
      - directory
      - filepath
      - hs-backend-booster
      - monad-logger
      - prettyprinter
      - text
      - transformers
    ghc-options:
      - -rtsopts
  count-aborts:
    source-dirs: count-aborts
    main: Main.hs
    dependencies:
      - aeson
      - base
      - bytestring
      - containers
      - directory
      - filepath
      - kore-rpc-types
      - text
    ghc-options:
      - -rtsopts
  process-logs:
    source-dirs: process-logs
    main: Main.hs
    dependencies:
      - aeson
      - aeson-pretty
      - base
      - bytestring
      - containers
      - directory
      - filepath
      - hs-backend-booster
      - kore-rpc-types
      - optparse-applicative
      - text
      - time
    ghc-options:
      - -rtsopts
  time-profile:
    source-dirs: time-profile
    main: Main.hs
    dependencies:
      - aeson
      - base
      - bytestring
      - containers
      - directory
      - filepath
      - kore-rpc-types
      - profiteur
      - text
      - unordered-containers
      - vector
    ghc-options:
      - -rtsopts
  parsetest-binary:
    source-dirs: parsetest-binary
    main: ParsetestBinary.hs
    dependencies:
      - base
      - binary
      - bytestring
      - containers
      - hs-backend-booster
      - text
    ghc-options:
      - -rtsopts
  pretty:
    source-dirs: pretty
    main: Pretty.hs
    dependencies:
      - base
      - aeson
      - bytestring
      - hs-backend-booster
      - prettyprinter
      - text
      - transformers
    ghc-options:
      - -rtsopts
  kore-json-differ:
    source-dirs: kore-json-differ
    main: Main.hs
    dependencies:
      - base
      - bytestring
      - containers
      - hs-backend-booster
    ghc-options:
      - -rtsopts
  kore-rpc-dev:
    source-dirs: kore-rpc-dev
    main: Server.hs
    dependencies:
      - aeson
      - base
      - bytestring
      - clock
      - conduit-extra
      - containers
      - exceptions
      - fast-logger
      - hs-backend-booster
      - json-rpc
      - kore
      - kore-rpc-types
      - monad-logger
      - optparse-applicative
      - text
      - transformers
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
  kore-match-disjunction:
    source-dirs: kore-match-disjunction
    main: Main.hs
    dependencies:
      - base
      - clock
      - kore
      - optparse-applicative
      - transformers
    ghc-options:
      - -rtsopts
  kore-parser:
    source-dirs: kore-parser
    main: Main.hs
    dependencies:
      - base
      - bytestring
      - containers
      - exceptions
      - kore
    ghc-options:
      - -rtsopts
