---
name: Performance Test and Report Generation
description: Provide test file and CI will generate a report for further investigation 
title: "[Haskell-Performance] <Title>"
labels: ["performance", "haskell-backend"]
body:
  - type: markdown
    attributes:
      value: |
        # Performance Test Form & Report Generator
        ## -- For Internal Use Only -- 
        Test Data will only be generated for RV Organization users 
        1. Please attach test file to kick off tests
        
        Results will be attached to the created issue after testing completes
  - type: textarea
    attributes:
      label: Please Prepare Test Data
      placeholder: < Drag and Drop file here >
    validations:
      required: true
