DEF = search
include $(CURDIR)/../include.mk

initial-breadth-limit.search.final.search.out: KORE_EXEC_OPTS += --breadth 1
initial-breadth-limit.search.one.search.out: KORE_EXEC_OPTS += --breadth 1
initial-breadth-limit.search.plus.search.out: KORE_EXEC_OPTS += --breadth 1
initial-breadth-limit.search.star.search.out: KORE_EXEC_OPTS += --breadth 1
