#!/usr/bin/env bash

set -exuo pipefail

export TOP=${TOP:-$(git rev-parse --show-toplevel)}
UPSTREAM_REMOTE=${UPSTREAM_REMOTE:-origin}
UPSTREAM_BRANCH=master
BRANCH_NAME=update-k-nightly

$TOP/scripts/git-assert-clean.sh

if [[ $(git rev-parse HEAD) != $(git rev-parse $UPSTREAM_BRANCH) ]]; then
    echo "Must run with $UPSTREAM_BRANCH checked out!!!"
    exit 1
fi

$TOP/scripts/update-k-nightly.sh

if $TOP/scripts/git-assert-clean.sh; then
    echo "No update..."
    exit 0
fi

git checkout -B "$BRANCH_NAME" "$UPSTREAM_REMOTE/$UPSTREAM_BRANCH"

git add $TOP/deps/k_release

git commit --message 'deps/k_release: update K nightly version'

hub pull-request --push --force --head "$BRANCH_NAME" --base "$UPSTREAM_BRANCH" --reviewer vladciobanu --file - <<MSG
Update K Nightly version used for integration testing

PR generated by '$0'
MSG
