name: 'With Docker'
description: 'Run a given stage with Docker Image'
inputs:
  tag:
    description: 'Docker image tag to use'
    required: true
  subdir:
    description: 'Subdirectory where code is cloned.'
    required: false
    default: ''
  os:
    description: 'OS to setup Docker for.'
    required: true
  distro:
    description: 'Distribution to setup Docker for.'
    required: true
  hlint:
    description: 'hlint version to use.'
    required: true
  hpack:
    description: 'hpack version to use.'
    required: true
  fourmolu:
    description: 'fourmolu version to use.'
    required: true
  ghc:
    description: 'ghc version to use (determine base image)'
    required: true
  dockerfile:
    description: 'Hardcode the path of the dockerfile to use.'
    required: false
    default: .github/workflows/Dockerfile
  docker-run-args:
    description: 'Extra arguments to pass to docker run.'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
  - name: 'Set up Docker'
    shell: bash {0}
    env:
      TAG_NAME: ${{ inputs.tag }}
      SUBDIR: ${{ inputs.subdir }}
      BASE_OS: ${{ inputs.os }}
      BASE_DISTRO: ${{ inputs.distro }}
      HLINT_VERSION: ${{ inputs.hlint }}
      HPACK_VERSION: ${{ inputs.hpack }}
      GHC_VERSION: ${{ inputs.ghc }}
      FOURMOLU_VERSION: ${{ inputs.fourmolu }}
      DOCKERFILE: ${{ inputs.dockerfile }}
      DOCKER_RUN_ARGS: ${{ inputs.docker-run-args }}
    run: |
      set -euxo pipefail

      USER=$(id -un)
      USER_ID=$(id -u)
      GROUP=$(id -gn)
      GROUP_ID=$(id -g)

      docker build . --file ${SUBDIR}${DOCKERFILE}                    \
          --tag runtimeverification/${TAG_NAME}                       \
          --build-arg BASE_OS=${BASE_OS}                              \
          --build-arg BASE_DISTRO=${BASE_DISTRO}                      \
          --build-arg HPACK_VERSION=${HPACK_VERSION}                  \
          --build-arg HLINT_VERSION=${HLINT_VERSION}                  \
          --build-arg GHC_VERSION=${GHC_VERSION}                      \
          --build-arg FOURMOLU_VERSION=${FOURMOLU_VERSION}            \
          --build-arg USER=${USER} --build-arg USER_ID=${USER_ID}     \
          --build-arg GROUP=${GROUP} --build-arg GROUP_ID=${GROUP_ID}

      docker run                             \
          --name ${TAG_NAME}                 \
          --rm -it                           \
          --detach                           \
          --workdir /opt/workspace/${SUBDIR} \
          --user ${USER}:${GROUP}            \
          -v "$(pwd):/opt/workspace"         \
          -v "/etc/passwd:/etc/passwd:ro"    \
          -v "/etc/group:/etc/group:ro"      \
          ${DOCKER_RUN_ARGS}                 \
          runtimeverification/${TAG_NAME}
