name:                kore
version:             0.38.0.0
github:              "kframework/kore"
license:             NCSA
license-file:        LICENSE
author:              "Runtime Verification Inc"
maintainer:          "thomas.tuegel@runtimeverification.com"
copyright:           "2018-2020 Runtime Verification Inc"
category:            Language

extra-source-files:
  - README.md
  - CHANGELOG.md

data-dir: data

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the [README](README.md) file.

flags:
  threaded:
    description: Use the threaded runtime. Recommended to disable for profiling.
    manual: true
    default: true
  release:
    description: Build a faster runtime, at the expense of a slower build.
    manual: true
    default: false

dependencies:
  - base >=4.7
  - adjunctions >=4.4
  - aeson >=1.4
  - array >=0.5
  - async >=2.2
  - bytestring >=0.10
  - comonad >=5.0
  - containers >=0.5.8
  - clock >=0.8
  - co-log >=0.3
  - cryptonite >=0.25
  - data-default >=0.7
  - deepseq >=1.4
  - directory >=1.3
  - distributive >=0.6
  - errors >=2.3
  - exceptions >=0.10
  - extra >=1.6
  - fgl >=5.7
  - free >=5.1
  - filepath >=1.4
  - generic-lens >=1.1
  - generics-sop >=0.5
  - ghc-trace-events >= 0.1
  - gitrev >=1.3
  - graphviz >=2999.20
  - groom >=0.1
  - hashable >=1.2
  - haskeline >=0.7
  - integer-gmp >=1.0
  - lens >=4.17
  - logict >=0.7
  - megaparsec >= 7.0.4
  - memory >=0.14
  - mmorph >=1.1
  - mtl >=2.2
  - optparse-applicative >=0.14
  - parser-combinators >=1.1
  - prettyprinter >=1.2
  - process >=1.6
  - profunctors >=5.3
  - recursion-schemes >=5.1
  - reflection >=2.1
  - semialign >=1
  - sqlite-simple >=0.4
  - streams
  - stm >=2.5
  - tar >= 0.5
  - template-haskell >=2.14
  - temporary >=1.3
  - text >=1.2
  - these >=1.0
  - time >=1.8
  - transformers >=0.4
  - unordered-containers >=0.2
  - vector >= 0.12
  - witherable >=0.3
  - zlib >= 0.6

build-tools:
  - tasty-discover:tasty-discover >=4.2

default-extensions:
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingVia
  - DuplicateRecordFields
  - EmptyCase
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - TypeSynonymInstances
  - UndecidableInstances
  - ViewPatterns

ghc-options:
  - -fno-ignore-asserts
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wmissing-export-lists

when:
  - condition: "!flag(release)"
    ghc-options:
      - -fno-specialise


library:
  source-dirs: src

_common-exe: &common-exe
  ghc-options: -eventlog
  when:
    - condition: flag(threaded)
      then:
        ghc-options: -threaded -rtsopts "-with-rtsopts=-N -T -A32M -qn4"
      else:
        ghc-options: -rtsopts "-with-rtsopts=-A32M -T"

executables:
  kore-parser:
    main: Main.hs
    source-dirs:
      - app/parser
      - app/share
    dependencies:
      - kore
    <<: *common-exe

  kore-exec:
    main: Main.hs
    source-dirs:
      - app/exec
      - app/share
    dependencies:
      - kore
    <<: *common-exe

  kore-format:
    main: Main.hs
    source-dirs:
      - app/format
      - app/share
    dependencies:
      - kore
    <<: *common-exe

  kore-repl:
    main: Main.hs
    source-dirs:
      - app/repl
      - app/share
    dependencies:
      - kore
    <<: *common-exe

  kore-prof:
    main: Main.hs
    source-dirs:
      - app/prof
    dependencies:
      - eventlog2speedscope
      - optparse-applicative

tests:
  kore-test:
    main: Test.hs
    source-dirs:
      - test
    dependencies:
      - kore
      - QuickCheck >=2.13
      - call-stack >=0.1
      - hedgehog >=1.0
      - quickcheck-instances >=0.3
      - tasty >=1.2
      - tasty-golden >=2.3
      - tasty-hunit >=0.10
      - tasty-hedgehog >=1.0
      - tasty-quickcheck >=0.10
      - tasty-test-reporter >=0.1
      - template-haskell >=2.14
      - temporary >=1.3
    <<: *common-exe
