name:                language-kore
version:             0.0.1.0
github:              "kframework/kore"
license:             OtherLicense
license-file:        LICENSE
author:              "Virgil Serbanuta"
maintainer:          "virgil.serbanuta@runtimeverification.com"
copyright:           "2018 Runtime Verification Inc"
category:            Language

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: |
  Please see the README on Github at <https://github.com/kframework/kore/blob/master/src/main/haskell/language-kore/README.md>

dependencies:
  - base >= 4.7
  - array
  - bytestring >= 0.10
  - bytestring-trie
  - containers
  - unordered-containers
  - clock
  - data-fix
  - deepseq
  - gitrev
  - groom
  - hashable
  - lens
<<<<<<< HEAD
  - megaparsec >=6.4.0
=======
  - megaparsec >= 6.4.0
  - mtl
  - optparse-applicative
  - parser-combinators
  - prettyprinter
  - reflection
  - time
<<<<<<< HEAD

build-tools:
  - tasty-discover

library:
  source-dirs: src
  default-extensions:
    - LambdaCase
    - OverloadedStrings

executables:
  kore-parser:
    main:                Main.hs
    source-dirs:
      - app/parser
      - app/share
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - language-kore

  kore-format:
    main: Main.hs
    source-dirs:
      - app/format
      - app/share
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    default-extensions:
      - RecordWildCards
    dependencies:
      - language-kore

  kore-format:
    main: Main.hs
    source-dirs: app/format
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    default-extensions:
      - RecordWildCards
    dependencies:
      - language-kore

  kore-format:
    main: Main.hs
    source-dirs: app/format
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    default-extensions:
      - RecordWildCards
    dependencies:
      - language-kore

tests:
  kore-parser-test:
    main: Driver.hs
    source-dirs:
      - test
      - test/parser
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - language-kore
      - call-stack
      - directory >= 1.2.2
      - filepath
      - QuickCheck
      - tasty
      - tasty-ant-xml
      - tasty-hunit
      - tasty-golden
      - tasty-quickcheck
      - template-haskell
    default-extensions:
      - GADTs
