name: 'Update'
on:
  push:
    branches-ignore:
      - 'master'
  pull_request:
jobs:
  fourmolu:
    name: 'Style'
    runs-on: ubuntu-22.04
    steps:
      - name: Dummy workflow message
        run: |
          echo "The `Update` workflow is obsolete, this is just a placeholder" | tee -a $GITHUB_STEP_OUTPUT
